apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-playground-be
  labels:
    app: devops-playground-be
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devops-playground-be
  template:
    metadata:
      labels:
        app: devops-playground-be
    spec:
      containers:
        - name: devops-playground-be
          image: 300698/github-action:main-dc1339c
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: devops-playground-be-config
                  key: NODE_ENV
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: devops-playground-be-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: devops-playground-be-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: devops-playground-be-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: devops-playground-be-config
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: devops-playground-be-config
                  key: DB_DATABASE
          volumeMounts:
            - name: app-storage
              mountPath: /usr/src/app/data
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: devops-playground-pvc
          
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-playground-be-config
data:
  NODE_ENV: NODE_ENV-local-ne
  DB_HOST: devops-playground-postgres-service
  DB_PORT: "5432"
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: mydb
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-playground-be-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-playground-be
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: "20m"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
