apiVersion: v1
kind: Service
metadata:
  name: devops-playground-be
spec:
  selector:
    app: devops-playground-be
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30081
  type: NodePort
