apiVersion: v1
kind: Service
metadata:
  name: devops-playground-be
  labels:
    app: devops-playground-be
spec:
  selector:
    app: devops-playground-be
  ports:
    - name: http
      port: 88
      targetPort: 3000
      #nodePort: 30081
  type: ClusterIP
