resources:
  - ../../base
  - postgres-alias.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: 300698/github-action
    newName: 300698/github-action
    newTag: main-046329b

nameSuffix: -dev

patches:
  - path: ingress-patch.yaml
  - path: configmap-patch.yaml

