resources:
  - ../../base
  - postgres-alias.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

nameSuffix: -dev

patches:
  - path: ingress-patch.yaml
  - path: configmap-patch.yaml
  - path: resources-patch.yaml
  - path: hpa-patch.yaml


