apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-playground-be
  labels:
    app: devops-playground-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-playground-be
  template:
    metadata:
      labels:
        app: devops-playground-be
    spec:
      containers:
      - name: devops-playground-be
        image: 300698/github-action:main-c58ddc260a27bd1d12035ac55b8017645963a0c3
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
