apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: default
spec:
  rules:
  - host: webapptest.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-playground-be
            port:
              number: 80
