resources:
- ../../base
- postgres-db.yaml
- pgadmin.yaml
- pgadmin-ingress.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
patches:
- path: resources-patch.yaml
- path: hpa-patch.yaml
