resources:
- ../../base
- postgres-db.yaml
- pgadmin.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
images:
- name: 300698/github-action
  newName: 300698/github-action
  newTag: main-30c67c8

patches:
- path: resources-patch.yaml
- path: hpa-patch.yaml
